sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MY+KeZ+BNwjOJOC+O/rxGfqBZTIE32Jg7Dt5wZ+H+XY3rwHGGMMa+lyDZK/y0yGSfe2ovoGiaa6LLPy0rR+Sv0fhxQTzcTrKLbphKJnXTrHRNppe7untosMYmABeW8tK8fFlVC8DQSQ2qcpGgbijVPPGuMa1Y9o+kCkolZ2mn80KMZEWdH3mVSV+dgmKjl4z/JBZcni+5GaK/FCfBWSKOdRPxmMxqSWnMgYfbMJwVMJbso/H1q1T8e4aWFTaF5hD/XrxuS4nCGMfkpylbJoJYDSDLrOZDxJgx7qsqLhElo52lTzk3ZctabZbdfKPloyA2CLcq4Ijtdeq72RNKb+MAO9eeetj53Z5Sgue7DjLeq0xnslZuwoMNh6E/Ms9kLbZt4hZbhRPyc6ira3iSQLxgyh2Q9Ie+QnC/f2K0+hDrbjiBmwG3t6XscpcDOAefkEuZAU63o4n36OpJiOnppm/Q2GKDLLUEeARphmCiKGRukeL2hijFf1g5rAvtJWJ2a+smuGLfFlalQKGeXhMKoWLPVHcWsZNzjxotlT1CLS/cL/GoT0rGzWWzCxR3ljiuM77EPAhrFfyzAZDuYlaiyyuVjujptkjvkBq5KszczRoUBB6eRAo4J1MJk3RUYgkf6YsEVM5sYN2Kt+2pOcEo5TNpW6cYCaEtvLaG8fKgaPdVoo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/L-Ingenu_4651
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy